# Generated by Django 5.2.4 on 2025-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_address_line_1_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='profile'),
        ),
    ]
