# Generated by Django 5.2.4 on 2025-07-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='profile_picture',
            field=models.ImageField(blank=True, default='about_page/about.png', null=True, upload_to='about_page'),
        ),
    ]
